// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClientOptions } from '@supabase/supabase-js';
import type { Database } from './types';

type StorageAdapter = NonNullable<SupabaseClientOptions['auth']>['storage'];

export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
export const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const createMemoryStorage = (): StorageAdapter => {
  const store = new Map<string, string>();
  return {
    getItem: (key) => store.get(key) ?? null,
    setItem: (key, value) => {
      store.set(key, value);
    },
    removeItem: (key) => {
      store.delete(key);
    },
  };
};

const resolveStorage = (): StorageAdapter => {
  if (typeof window === 'undefined') return createMemoryStorage();

  try {
    const testKey = '__supabase_storage_test__';
    window.localStorage.setItem(testKey, '1');
    window.localStorage.removeItem(testKey);
    return window.localStorage;
  } catch (error) {
    console.warn('Falling back to in-memory auth storage (localStorage unavailable)', error);
    return createMemoryStorage();
  }
};

const assertEnv = () => {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error('Supabase environment variables are missing. Please configure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.');
  }
};

assertEnv();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: resolveStorage(),
    persistSession: true,
    autoRefreshToken: true,
  },
});
