// This file is automatically generated. Do not edit it directly.
import * as supabaseJs from '@supabase/supabase-js';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

type StorageAdapter = Pick<Storage, 'getItem' | 'setItem' | 'removeItem'>;

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const buildMissingEnvMessage = (url?: string, key?: string) => {
  const missing: string[] = [];

  if (!url) missing.push('VITE_SUPABASE_URL');
  if (!key) missing.push('VITE_SUPABASE_PUBLISHABLE_KEY');

  return `Supabase configuration is missing: ${missing.join(
    ', '
  )}. Set these environment variables to initialize Supabase.`;
};

const createNoopClient = (message: string): SupabaseClient<Database> => {
  return new Proxy({} as SupabaseClient<Database>, {
    get: () => {
      throw new Error(message);
    },
  });
};

export const createSupabaseStorage = (
  currentWindow: typeof window | undefined = typeof window !== 'undefined' ? window : undefined
): StorageAdapter => {
  if (!currentWindow || !currentWindow.localStorage) {
    const memoryStore = new Map<string, string>();

    return {
      getItem: (key: string) => memoryStore.get(key) ?? null,
      setItem: (key: string, value: string) => {
        memoryStore.set(key, value);
      },
      removeItem: (key: string) => {
        memoryStore.delete(key);
      },
    };
  }

  return currentWindow.localStorage;
};

export const createSupabaseClient = (options?: {
  url?: string;
  key?: string;
  storage?: StorageAdapter;
}): SupabaseClient<Database> => {
  const supabaseUrl = options?.url ?? SUPABASE_URL;
  const supabaseKey = options?.key ?? SUPABASE_PUBLISHABLE_KEY;
  const storage = options?.storage ?? createSupabaseStorage();

  if (!supabaseUrl || !supabaseKey) {
    const message = buildMissingEnvMessage(supabaseUrl, supabaseKey);
    return createNoopClient(message);
  }

  return supabaseJs.createClient<Database>(supabaseUrl, supabaseKey, {
    auth: {
      storage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
};

export const supabase = createSupabaseClient();

if (import.meta.vitest) {
  const { describe, expect, it, vi } = import.meta.vitest;

  describe('createSupabaseStorage', () => {
    it('falls back to an in-memory store when window is unavailable (SSR)', () => {
      const storage = createSupabaseStorage(undefined);

      storage.setItem('token', 'value');
      expect(storage.getItem('token')).toBe('value');
      storage.removeItem('token');
      expect(storage.getItem('token')).toBeNull();
    });

    it('uses provided localStorage when running in a PWA context', () => {
      const data: Record<string, string> = {};
      const fakeWindow = {
        localStorage: {
          getItem: vi.fn((key: string) => data[key] ?? null),
          setItem: vi.fn((key: string, value: string) => {
            data[key] = value;
          }),
          removeItem: vi.fn((key: string) => {
            delete data[key];
          }),
        },
      } as unknown as Window;

      const storage = createSupabaseStorage(fakeWindow);

      storage.setItem('session', 'abc');
      expect(fakeWindow.localStorage.setItem).toHaveBeenCalledWith('session', 'abc');
      storage.removeItem('session');
      expect(fakeWindow.localStorage.removeItem).toHaveBeenCalledWith('session');
    });
  });

  describe('createSupabaseClient', () => {
    it('returns a no-op client with a descriptive error when env vars are missing', () => {
      const client = createSupabaseClient({ url: '', key: '', storage: createSupabaseStorage(undefined) });

      expect(() => (client as unknown as Record<string, unknown>).from).toThrow(
        /Supabase configuration is missing: VITE_SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY/
      );
    });

    it('passes the provided storage to Supabase when configuration is present', () => {
      const storage = createSupabaseStorage(undefined);
      const createClientSpy = vi
        .spyOn(supabaseJs, 'createClient')
        .mockReturnValue({} as SupabaseClient<Database>);

      createSupabaseClient({
        url: 'https://example.supabase.co',
        key: 'public-anon-key',
        storage,
      });

      expect(createClientSpy).toHaveBeenCalledWith(
        'https://example.supabase.co',
        'public-anon-key',
        expect.objectContaining({
          auth: expect.objectContaining({ storage }),
        })
      );

      createClientSpy.mockRestore();
    });
  });
}
